name: flutterdemo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.1+1
  cached_network_image: ^2.3.1
  dio: ^3.0.10 #latest version
  provider: ^3.0.0+1
  json_annotation: ^3.0.1
  event_bus: ^1.1.1
  flutter_custom_bottom_tab_bar:
    git: https://github.com/LiuC520/flutter_custom_bottom_tab_bar.git
  flutter_staggered_grid_view: ^0.3.2
  webview_flutter: 
    path: ./webview_flutter_hack/
#   spark_share: 
#     path: ./spark_share/
  usth_spark_share: 
    path: ./usth_spark_share/
#   webview_flutter: ^0.3.24
  auto_orientation: ^1.0.5 
  video_player: ^0.10.12+2
  open_iconic_flutter: ^0.3.0
  fluttertoast: ^7.1.1
#   flt_video_player: ^0.0.4
#   chewie: ^0.9.10
#   fijkplayer:
#     git:
#       url: https://github.com/befovy/fijkplayer.git
#       ref: develop # can be replaced to branch or tag name
  wakelock: ^0.1.4+2
  common_utils: ^1.1.3
#   fluwx: ^2.3.0
  permission_handler: ^5.0.1+1
#   flutter_inappwebview: ^4.0.0+4
  url_launcher: ^5.6.0
  flutter_downloader: ^1.5.0
  share: ^0.6.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter 
  json_serializable: ^3.2.0
  build_runner: ^1.7.4
  json_to_model: ^1.4.0
  flutter_native_splash: ^0.1.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  image: assets/images/logo.png
  color: "61bab3"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
