name: flutter_unionad
description: A flutter plugin for Bytedance-UnionAD.It is convenient for Android and IOS to directly call the method and native view of advertisement SDK.
version: 0.0.7
homepage: https://github.com/gstory0404/flutter_unionad

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gstory.flutter_unionad
        pluginClass: FlutterUnionadPlugin
      ios:
        pluginClass: FlutterUnionadPlugin
