#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/spark/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/spark/Documents/flutter/myFlutter/flutterdemo/webview_flutter_hack"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/spark/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=0.3.24"
export "FLUTTER_BUILD_NUMBER=0.3.24"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
